### PR TITLE
Refactoring of launch and config files

### LINKED ISSUE #1: Refactoring and cleaning this repository
Hey, I moved the realsense-related repos from gitlab to github. Now, I would like to put an order into this repository. I added you (@matemat13, @petrlmat, @petrapa6, @kratkvit, @stibipet, @pritzvac) as assignees since you probably work often with realsense and might have an idea about what is really used and needed. If you could help me with the following:

- [X] I officially forked the _realsense-ros_ package (previously on our gitlab, as _realsense2_camera_) and pushed the currently-used head as the new **master**. I think there is nothing more to be done here..
- [x] Please, clean up the launch files and the config files in this meta-package. There are more launch files here than in the whole MRS system. I would like to see ideally one general launch file, or maybe one per realsense type.
- [x] Please, check the readme. I have a suspicion that some part of it relates to the Bluefox package. Is it still up to date? Moreover, is the readme general enough (for all realsense types).
- [X] The installation scripts should be updated as well, to be compatible with unattended installation on github actions. I (@klaxalk) will take care of that.
- [X] It looks like the installation script is not patching the kernel. Should not we do it?

Thanks

### PR DESCRIPTION
**Pull request by klaxalk**
We should end up with ideally 1 launch file, and 1 launch file per device at most.

The launch file should be all parametric, so normal users should not need to push their custom changes into this repository.

### CODE REVIEW

**Comment by pritzvac** [comment]
I added another launch file for 2 cameras using the same parameters, which includes the uav.launch. I also provided the path to the high-acc JSON config to the launch files, as it wasn't there. And I changed the 'rs_d435' topic and TF namespace to 'rgbd' since we use the same stuff for different models than D435 as well (I can change it in the simulation as well so that it corresponds). Do you agree with these changes?

**Review by matemat13 — APPROVED** [review]
seems fine to me, but why a special `uav_2_cameras.launch`?

**Comment by pritzvac** [comment]
I think it's useful to have an example launch file for how to run multiple cameras simultaneously - as it requires launching separate nodelet for each camera and passing the camera's serial number to know which camera is which. So that people don't need to reinvent the wheel when they want to use multiple cameras.

**Comment by klaxalk** [comment]
> 

I would then name with an "example" in the name.

**Comment by pritzvac** [comment]
Ok, I can rename it. Btw I edited sensors.launch in mrs_uav_general to use the new launch files and removed all realsense options apart from realsense_front and realsense_up_down (there was e.g. realsense_fire, realsense_brick etc.). Or do we want to keep just realsense_front there?

**Comment by matemat13** [comment]
good call with `sensors.launch`! We probably don't need any other realsenses there anymore. I'd just keep the most common varians - front and up/down.

**Comment by klaxalk** [comment]
I am for heaving up/down/front in the sensors.launch. Others are special and should be run manually by the user... I will should check `sensors.launch` myself. Are we running a dedicated nodelet manager for each of the sensors?

**Pull request merged**
